import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export  function Headline(props) {
  return (
      <div>
          <Head>
              <title>{ props.page} page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
           </Head>
          <ol>
            <li>
              Get started by editing <code>src/pages/{props.page}.js</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

    </div>
  );
}
